@startuml Controllers - Couche application

skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 30
skinparam ranksep 40

title Controllers - Couche Application

abstract class Controller {
  + render(view, data): void
}

class HomeController extends Controller {
  - ressourceModel: Ressource
  - themeModel: Theme
  + index(): void
}

class AuthController extends Controller {
  - userModel: Utilisateur
  + login(): void
  + register(): void
  + logout(): void
}

class CatalogueController extends Controller {
  - ressourceModel: Ressource
  + index(): void
  + nouveautes(): void
  + top(): void
  + search(): void
}

class RessourceController extends Controller {
  - ressourceModel: Ressource
  - evaluationModel: Evaluation
  + show(): void
}

class AdminController extends Controller {
  + index(): void
}

class LivreController extends Controller {
  - livreModel: Livre
  - genreModel: Genre
  - themeModel: Theme
  + index(): void
  + create(): void
  + edit(): void
  + delete(): void
}

class FilmController extends Controller {
  - filmModel: Film
  + index(): void
  + create(): void
  + edit(): void
  + delete(): void
}

class GenreController extends Controller {
  - genreModel: Genre
  + index(): void
  + create(): void
  + delete(): void
}

class EvaluationController extends Controller {
  - evaluationModel: Evaluation
  + createPost(): void
}

note left of LivreController
  **CRUD complet**
  Réservé au staff
end note

@enduml
